version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8000"  # Map port 8080 on host to 8000 in container
    networks:
      - laravel-network
    depends_on:
      - mysql
      - redis

  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-horizon
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: horizon
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network
    command: php artisan horizon
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: blackscale
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge